export const destinations = [
    {
        id: 'mirissa',
        title: "Airport to Mirissa",
        name: "Mirissa",
        price: 59,
        badge: "Top Choice",
        img: "/mirissa-new-fix.png",
        meta: "Whale Watching Hub",
        description: "Mirissa is a stunning beach town on Sri Lanka’s south coast, famous for its whale watching, coconut palm-fringed beaches, and vibrant nightlife.",
        longDescription: "Mirissa is a crescent-shaped beach on the southern tip of Sri Lanka, offering a laid-back tropical vibe. Known globally as a premier whale-watching destination, it also features the iconic Coconut Tree Hill and a variety of beachfront cafes. Whether you're looking for world-class surfing at the reef break or a quiet sunset at Secret Beach, Mirissa caters to every traveler.",
        bestTimeToVisit: "November to April (Dry season, best for whale watching)",
        localAttractions: ["Whale Watching Safaris", "Coconut Tree Hill", "Parrot Rock", "Secret Beach", "Surfing at the Main Break"],
        faqs: [
            { q: "How long does a taxi take from Colombo Airport to Mirissa?", a: "Typically 2.5 to 3 hours via the Southern Expressway." },
            { q: "Are there tolls included in the price?", a: "No, highway tolls are payable directly by the passenger." }
        ],
        distance: "150 km",
        time: "2.5 hours",
        highlights: ["Whale Watching", "Coconut Tree Hill", "Secret Beach", "Surfing"],
        pricing: { "Mini Car": 59, "Sedan": 65, "Mini Van": 75, "KDH Van": 85 },
        coords: { lat: 5.9483, lon: 80.4716 },
        fullAddress: "Mirissa, Sri Lanka",
        seoTitle: "Mirissa Taxi & Day Tours | Airport Taxi & Private Transfers to Any Destination in Sri Lanka",
        seoDescription: "Book the best Mirissa Taxi for day tours, airport taxi transfers, and private trips. Travel from Mirissa to any destination in Sri Lanka with a safe, comfortable, reliable, and affordable taxi service. Enjoy hassle-free airport transfers and sightseeing tours with experienced drivers.",
        seoKeywords: [
            "Mirissa Taxi",
            "Mirissa Taxi Service",
            "Mirissa Day Tour",
            "Mirissa Day Tours",
            "Mirissa Airport Taxi",
            "Mirissa Airport Transfer",
            "Mirissa to Colombo Airport Taxi",
            "Mirissa to Any Destination",
            "Mirissa Private Taxi",
            "Mirissa Sightseeing Tours",
            "Sri Lanka Private Taxi",
            "Sri Lanka Airport Taxi"
        ]
    },
    {
        id: 'ahangama',
        title: "Airport to Ahangama",
        name: "Ahangama",
        price: 58,
        badge: "Deep South",
        img: "/images/tours/ahangama.png",
        meta: "Surfing & Yoga Hub",
        description: "Ahangama is a charming coastal village known for its world-class surf breaks, stilt fishermen, and laid-back atmosphere.",
        longDescription: "Searching for the perfect surf break? Ahangama is Sri Lanka's rising star for surfing and yoga enthusiasts. This authentic coastal stretch is less crowded than neighbouring Mirissa, offering pristine beaches and the famous stilt fishermen. It's the ideal base for exploring the south coast while staying in boutique villas and ecological retreats.",
        bestTimeToVisit: "December to March (Perfect surfing conditions)",
        localAttractions: ["Stilt Fishing Spots", "Koggala Lake Safari", "Turtle Hatcheries", "Yoga & Wellness Retreats"],
        faqs: [
            { q: "Best way to travel from CMB Airport to Ahangama?", a: "Our private car service is the fastest, taking approx 2.5 hours." },
            { q: "Can I stop for food on the way?", a: "Yes, our drivers are happy to make brief stops at reputable rest areas." }
        ],
        distance: "160 km",
        time: "2.5 hours",
        highlights: ["Surfing", "Stilt Fishermen", "Yoga Retreats", "Koggala Lake"],
        pricing: { "Mini Car": 58, "Sedan": 64, "Mini Van": 75, "KDH Van": 85 },
        coords: { lat: 5.9723, lon: 80.3644 },
        fullAddress: "Ahangama, Sri Lanka"
    },
    {
        id: 'sigiriya',
        title: "Airport to Sigiriya",
        name: "Sigiriya",
        price: 90,
        badge: "Historic",
        img: "/sigiriya-new-hero.png",
        meta: "Ancient Rock Fortress",
        description: "Sigiriya is an ancient rock fortress dominated by a massive column of rock nearly 200 meters high. It is a UNESCO World Heritage Site.",
        longDescription: "Sigiriya, or 'Lion Rock', is a majestic 5th-century palace complex and fortress, rising 200m from the central plains. As a UNESCO World Heritage site, it showcases advanced ancient urban planning, stunning frescoes, and the famous Mirror Wall. Climbing to the summit reveals breathtaking 360-degree views of the surrounding jungle and ancient gardens.",
        bestTimeToVisit: "January to April or July to September",
        localAttractions: ["Lion Rock Summit", "Pidurangala Rock", "Minneriya Elephant Safari", "Dambulla Cave Temple"],
        faqs: [
            { q: "Is Sigiriya far from the airport?", a: "It is about 150 km, taking approximately 3.5 to 4 hours." },
            { q: "Is it better to leave early for Sigiriya?", a: "Yes, we recommend morning pickups to avoid traffic and climb the rock before the midday heat." }
        ],
        distance: "150 km",
        time: "3.5 hours",
        highlights: ["Sigiriya Lion Rock", "Pidurangala Rock", "Minneriya National Park", "Village Tour"],
        pricing: { "Mini Car": 90, "Sedan": 100, "Mini Van": 115, "KDH Van": 130 },
        coords: { lat: 7.9570, lon: 80.7603 },
        fullAddress: "Sigiriya, Sri Lanka",
        seoTitle: "Sigiriya Taxi & Round Tours | Airport Transfers, Hotel Transfers & Private Taxi Sri Lanka",
        seoDescription: "Book reliable Sigiriya Taxi services in Sri Lanka for round tours, hotel transfers, airport transfers and private trips to any destination. Enjoy comfortable, safe and affordable taxi rides with professional drivers. Explore Sigiriya and travel Sri Lanka with ease.",
        seoKeywords: [
            "Sigiriya Taxi",
            "Sigiriya Taxi Service",
            "Sigiriya Private Taxi",
            "Sigiriya Airport Transfer",
            "Sigiriya Airport Taxi",
            "Sigiriya Hotel Transfer",
            "Sigiriya Round Tour",
            "Sigiriya Day Tour",
            "Private Taxi Sigiriya",
            "Colombo Airport to Sigiriya Taxi",
            "Sigiriya to Colombo Airport Taxi",
            "Sigiriya to Any Destination",
            "Sigiriya Private Tours",
            "Sigiriya Taxi & Tours",
            "Sri Lanka Private Taxi Service"
        ]
    },
    {
        id: 'ella',
        title: "Airport to Ella",
        name: "Ella",
        price: 110,
        badge: "Scenic Route",
        img: "/Hero/ella.jpg",
        meta: "Highlands Escape",
        description: "Ella is a small town in the Badulla District of Uva Province, Sri Lanka. It is approximately 200 kilometres east of Colombo.",
        longDescription: "Ella is a mountain village nestled in the central highlands, famous for its emerald tea plantations and dramatic mountain views. The iconic Nine Arch Bridge and the hike up Little Adam’s Peak are absolute must-dos. With its cool climate and vibrant cafe culture, Ella is the ultimate destination for hikers and nature lovers alike.",
        bestTimeToVisit: "January to March",
        localAttractions: ["Nine Arch Bridge", "Little Adam's Peak", "Ravana Falls", "Ella Rock Hike", "Tea Factory Tours"],
        faqs: [
            { q: "How long is the drive to Ella?", a: "The drive takes about 5 to 6 hours depending on traffic and visibility in the hills." },
            { q: "Can we see scenery on the way?", a: "Absolutely! The drive through the tea country is one of the most beautiful in the world." }
        ],
        distance: "210 km",
        time: "5 hours",
        highlights: ["Nine Arch Bridge", "Teas Estates", "Waterfalls", "Hiking"],
        pricing: { "Mini Car": 110, "Sedan": 120, "Mini Van": 140, "KDH Van": 155 },
        coords: { lat: 6.8724, lon: 81.0466 },
        fullAddress: "Ella, Sri Lanka"
    },
    {
        id: 'kandy',
        title: "Airport to Kandy",
        name: "Kandy",
        price: 65,
        badge: "Cultural Capital",
        img: "/kandy-new.png",
        meta: "Hill Country Capital",
        description: "Kandy is a large city in central Sri Lanka. It's set on a plateau surrounded by mountains, home to tea plantations and rainforest.",
        longDescription: "The sacred city of Kandy is the spiritual heart of Sri Lanka, home to the Temple of the Sacred Tooth Relic. This UNESCO World Heritage site is nestled among mist-covered mountains and lush tea estates. Visitors can explore the Peradeniya Royal Botanical Gardens, witness traditional Kandyan dance performances, and enjoy the serene atmosphere around Kandy Lake.",
        bestTimeToVisit: "December to April",
        localAttractions: ["Temple of the Sacred Tooth Relic", "Royal Botanical Gardens", "Kandy Lake", "Bahirawakanda Buddha Statue"],
        faqs: [
            { q: "Is there a train from the airport to Kandy?", a: "No direct train. The most efficient way is a private taxi taking 3 hours." },
            { q: "Do drivers speak English?", a: "Yes, all our drivers are well-versed in English to assist our international guests." }
        ],
        distance: "103 km",
        time: "3 hours",
        highlights: ["Temple of the Tooth", "Kandy Lake", "Botanical Gardens", "Cultural Dance"],
        pricing: { "Mini Car": 65, "Sedan": 70, "Mini Van": 85, "KDH Van": 95 },
        coords: { lat: 7.2906, lon: 80.6337 },
        fullAddress: "Kandy, Sri Lanka"
    },
    {
        id: 'galle',
        title: "Airport to Galle",
        name: "Galle",
        price: 55,
        badge: "UNESCO Site",
        img: "/galle-new.png",
        meta: "Colonial Fort City",
        description: "Galle is a city on the southwest coast of Sri Lanka. It's known for Galle Fort, the fortified old city founded by Portuguese colonists.",
        longDescription: "Galle Fort is a living time capsule, blending European architectural styles and South Asian traditions. Declared a UNESCO World Heritage site, the fort's car-free streets are lined with boutique shops, art galleries, and historic churches. Beyond the fort, the surrounding coastline offers golden beaches like Unawatuna and pristine snorkeling spots.",
        bestTimeToVisit: "November to April",
        localAttractions: ["Galle Dutch Fort", "Lighthouse", "Dutch Reformed Church", "Marine Museum", "Sea Turtle Hatchery"],
        faqs: [
            { q: "Does the taxi use the highway to Galle?", a: "Yes, we use the Southern Expressway for a smooth 2-hour journey." },
            { q: "Can we visit the fort during the transfer?", a: "Our standard transfer is point-to-point, but custom tours can be arranged." }
        ],
        distance: "145 km",
        time: "2 hours",
        highlights: ["Galle Fort", "Lighthouse", "Dutch Museum", "Unawatuna Beach"],
        pricing: { "Mini Car": 55, "Sedan": 60, "Mini Van": 75, "KDH Van": 85 },
        coords: { lat: 6.0535, lon: 80.2210 },
        fullAddress: "Galle, Sri Lanka"
    },
    {
        id: 'arugambay',
        title: "Airport to Arugam Bay",
        name: "Arugam Bay",
        price: 180,
        badge: "Surfing Paradise",
        img: "/images/tours/arugambay.png",
        meta: "East Coast Vibes",
        description: "Arugam Bay is a world-famous surfing destination on the southeast coast, known for its dry zone climate and laid-back vibe.",
        distance: "320 km",
        time: "6.5 hours",
        highlights: ["Surfing Points", "Elephant Rock", "Kumana National Park", "Lagoon Safari"],
        pricing: { "Mini Car": 180, "Sedan": 195, "Mini Van": 210, "KDH Van": 230 },
        coords: { lat: 6.8400, lon: 81.8290 },
        fullAddress: "Arugam Bay, Sri Lanka"
    },
    {
        id: 'bentota',
        title: "Airport to Bentota",
        name: "Bentota",
        price: 45,
        badge: "Water Sports",
        img: "/images/tours/bentota.jpg",
        meta: "Golden Mile Beach",
        description: "Bentota is a resort town on Sri Lanka’s southwest coast, perfect for water sports and turtle conservation.",
        distance: "100 km",
        time: "1.5 hours",
        highlights: ["River Safari", "Brief Garden", "Water Sports", "Turtle Hatchery"],
        pricing: { "Mini Car": 45, "Sedan": 50, "Mini Van": 65, "KDH Van": 75 },
        coords: { lat: 6.4239, lon: 79.9942 },
        fullAddress: "Bentota, Sri Lanka"
    },
    {
        id: 'hikkaduwa',
        title: "Airport to Hikkaduwa",
        name: "Hikkaduwa",
        price: 50,
        badge: "Coral Sanctuary",
        img: "/hikkaduwa-new.png",
        meta: "Party & Dive",
        description: "Hikkaduwa is known for its marine sanctuary, vibrant nightlife, and great surfing spots in the southwest.",
        distance: "135 km",
        time: "2 hours",
        highlights: ["Coral Reef Snorkeling", "Turtle Hatchery", "Surfing", "Nightlife"],
        pricing: { "Mini Car": 50, "Sedan": 55, "Mini Van": 70, "KDH Van": 80 },
        coords: { lat: 6.1395, lon: 80.1058 },
        fullAddress: "Hikkaduwa, Sri Lanka"
    },
    {
        id: 'unawatuna',
        title: "Airport to Unawatuna",
        name: "Unawatuna",
        price: 58,
        badge: "Beach Lovers",
        img: "/unawatuna-new.png",
        meta: "Horseshoe Bay",
        description: "Unawatuna is a major tourist attraction, famous for its horseshoe-shaped beach and turquoise waters.",
        distance: "150 km",
        time: "2.5 hours",
        highlights: ["Jungle Beach", "Japanese Peace Pagoda", "Beach Parties", "Diving"],
        pricing: { "Mini Car": 58, "Sedan": 65, "Mini Van": 78, "KDH Van": 88 },
        coords: { lat: 6.0125, lon: 80.2483 },
        fullAddress: "Unawatuna, Sri Lanka"
    },
    {
        id: 'anuradhapura',
        title: "Airport to Anuradhapura",
        name: "Anuradhapura",
        price: 95,
        badge: "Ancient Capital",
        img: "/Hero/izanuradapura.jpg",
        meta: "Sacred City",
        description: "Anuradhapura is one of the ancient capitals of Sri Lanka, famous for its well-preserved ruins of ancient Lankan civilization.",
        distance: "170 km",
        time: "3.5 hours",
        highlights: ["Sri Maha Bodhi", "Ruwanwelisaya", "Isurumuniya", "Mihintale"],
        pricing: { "Mini Car": 95, "Sedan": 105, "Mini Van": 120, "KDH Van": 135 },
        coords: { lat: 8.3122, lon: 80.4131 },
        fullAddress: "Anuradhapura, Sri Lanka"
    },
    {
        id: 'nuwaraeliya',
        title: "Airport to Nuwara Eliya",
        name: "Nuwara Eliya",
        price: 105,
        badge: "Little England",
        img: "/nuwara-eliya-new.png",
        meta: "Tea Country",
        description: "Nuwara Eliya is the heart of the tea country, offering a temperate climate and colonial-era charm.",
        distance: "160 km",
        time: "4.5 hours",
        highlights: ["Tea Plantations", "Gregory Lake", "Horton Plains", "Victoria Park"],
        pricing: { "Mini Car": 105, "Sedan": 115, "Mini Van": 130, "KDH Van": 145 },
        coords: { lat: 6.9497, lon: 80.7891 },
        fullAddress: "Nuwara Eliya, Sri Lanka"
    },
    {
        id: 'yala',
        title: "Airport to Yala / Tissa",
        name: "Yala",
        price: 135,
        badge: "Safari Adventure",
        img: "/images/tours/yala.png",
        meta: "Leopard Kingdom",
        description: "Yala National Park is the most visited national park in Sri Lanka, home to a high density of leopards.",
        distance: "245 km",
        time: "4 hours",
        highlights: ["Safari Game Drive", "Sithulpawwa Rock", "Camping", "Bird Watching"],
        pricing: { "Mini Car": 135, "Sedan": 145, "Mini Van": 160, "KDH Van": 175 },
        coords: { lat: 6.3686, lon: 81.5204 },
        fullAddress: "Yala, Sri Lanka"
    },
    {
        id: 'trincomalee',
        title: "Airport to Trincomalee",
        name: "Trincomalee",
        price: 160,
        badge: "East Coast Gem",
        img: "/trincomalee-new.png",
        meta: "Nilaveli Beach",
        description: "Trincomalee is a beautiful port city on the northeast, offering some of the best beaches like Nilaveli.",
        distance: "235 km",
        time: "5 hours",
        highlights: ["Nilaveli Beach", "Pigeon Island", "Koneswaram Temple", "Marble Beach"],
        pricing: { "Mini Car": 160, "Sedan": 170, "Mini Van": 190, "KDH Van": 210 },
        coords: { lat: 8.5873, lon: 81.2152 },
        fullAddress: "Trincomalee, Sri Lanka"
    },
    {
        id: 'pasikudah',
        title: "Airport to Pasikudah",
        name: "Pasikudah",
        price: 175,
        badge: "Luxury Beach",
        img: "/pasikudah-new.png",
        meta: "Shallow Waters",
        description: "Pasikudah is famous for its pristine shallow waters and luxury resort developments on the east coast.",
        distance: "265 km",
        time: "5.5 hours",
        highlights: ["Pasikudah Beach", "Kalkudah Beach", "Luxury Resorts", "Water Sports"],
        pricing: { "Mini Car": 175, "Sedan": 185, "Mini Van": 200, "KDH Van": 220 },
        coords: { lat: 7.9220, lon: 81.5645 },
        fullAddress: "Pasikudah, Sri Lanka"
    },
    {
        id: 'tangalle',
        title: "Airport to Tangalle",
        name: "Tangalle",
        price: 130,
        badge: "Deep South",
        img: "/tangalle-new.png",
        meta: "Secluded Beaches",
        description: "Tangalle offers some of the most beautiful and secluded paradise beaches in southern Sri Lanka.",
        distance: "200 km",
        time: "3 hours",
        highlights: ["Goyambokka Beach", "Turtle Watch", "Mulkirigala Temple", "Lagoon Kayaking"],
        pricing: { "Mini Car": 130, "Sedan": 140, "Mini Van": 160, "KDH Van": 175 },
        coords: { lat: 6.0244, lon: 80.7937 },
        fullAddress: "Tangalle, Sri Lanka"
    },
    {
        id: 'wilpattu',
        title: "Airport to Wilpattu",
        name: "Wilpattu",
        price: 95,
        badge: "Jungle Safari",
        img: "/wilpattu-new.png",
        meta: "Land of Lakes",
        description: "Wilpattu is the largest and oldest national park in Sri Lanka, famous for its natural lakes.",
        distance: "140 km",
        time: "3 hours",
        highlights: ["Safari", "Leopards & Bears", "Camping", "Nature Trails"],
        pricing: { "Mini Car": 95, "Sedan": 105, "Mini Van": 120, "KDH Van": 135 },
        coords: { lat: 8.3514, lon: 80.0035 },
        fullAddress: "Wilpattu, Sri Lanka"
    },
    {
        id: 'colombo',
        title: "Airport to Colombo",
        name: "Colombo",
        price: 30,
        badge: "Commercial Capital",
        img: "/images/tours/colombo.png",
        meta: "City Life",
        description: "Colombo is the bustling commercial capital of Sri Lanka, offering a mix of modern life and colonial heritage.",
        distance: "35 km",
        time: "1 hour",
        highlights: ["Lotus Tower", "Galle Face Green", "Pettah Market", "National Museum"],
        pricing: { "Mini Car": 30, "Sedan": 35, "Mini Van": 45, "KDH Van": 55 },
        coords: { lat: 6.9271, lon: 79.8612 },
        fullAddress: "Colombo, Sri Lanka"
    },
    {
        id: 'udawalawa',
        title: "Airport to Udawalawa",
        name: "Udawalawa",
        price: 110,
        badge: "Elephant Kingdom",
        img: "/images/tours/udawalawa.png",
        meta: "Wildlife Safari",
        description: "Udawalawe National Park is renowned for its large population of wild elephants and beautiful reservoir landscapes.",
        distance: "165 km",
        time: "3.5 hours",
        highlights: ["Elephant Safari", "Udawalawe Reservoir", "Elephant Transit Home", "Bird Watching"],
        pricing: { "Mini Car": 110, "Sedan": 120, "Mini Van": 135, "KDH Van": 150 },
        coords: { lat: 6.4350, lon: 80.8872 },
        fullAddress: "Udawalawa, Sri Lanka"
    }
];
