import './globals.css'
import Navbar from '../components/Navbar'
import CategoryBar from '../components/CategoryBar'
import OfferMarquee from '../components/OfferMarquee'
import FloatingContact from '../components/FloatingContact'
import Footer from '../components/Footer'
import AuthProvider from '../components/AuthProvider'
import { ThemeProvider } from '../components/ThemeProvider'
import LiveChatWidget from '../components/LiveChatWidget'

export const metadata = {
    title: {
        default: 'Airport Taxis Pvt (Ltd) - Sri Lanka\'s #1 Airport Transfer & Tour Service',
        template: '%s | Airport Taxis Pvt (Ltd)'
    },
    description: '🚕 Sri Lanka\'s most trusted 24/7 Airport Taxi & Tour service. Book Colombo Airport (CMB) transfers, luxury KDH vans, and curated Sri Lanka tour packages. Fixed rates, professional English-speaking drivers, and instant online booking. Trusted by 10,000+ travelers for Colombo, Kandy, Galle, Sigiriya, and Mirissa transfers. Premium airport shuttle and private car service for all-island travel.',
    keywords: [
    "7 seater taxi",
    "airport bus",
    "airport booking taxi",
    "airport cab",
    "airport cab booking",
    "airport cab service",
    "airport cabs",
    "airport cabs near me",
    "airport car booking",
    "airport car service",
    "airport chauffeur service",
    "airport drop cab",
    "airport drop off service",
    "airport drop off taxi",
    "airport drop service",
    "airport hire",
    "airport minicab",
    "airport pick up",
    "airport pick up service",
    "airport pickup and drop off service",
    "airport price list",
    "airport rides",
    "airport service",
    "airport shuttle",
    "airport shuttle booking",
    "airport shuttle service",
    "airport shuttle service near me",
    "airport shuttle sri lanka",
    "airport taxi",
    "airport taxi booking",
    "airport taxi fare",
    "airport taxi flat rate",
    "airport taxi hire",
    "airport taxi near me",
    "airport taxi phone number",
    "airport taxi pick up",
    "airport taxi pickup",
    "airport taxi price",
    "airport taxi price list",
    "airport taxi prices",
    "airport taxi quote",
    "airport taxi rates",
    "airport taxi reviews",
    "airport taxi schiphol",
    "airport taxi service",
    "airport taxi service near me",
    "airport taxi sri lanka",
    "airport taxi transfer",
    "airport taxi transfers",
    "airport taxi transfers reviews",
    "airport taxi transport",
    "airport taxi van",
    "airport taxi with car seat",
    "airport to airport shuttle",
    "airport transfer",
    "airport transfer colombo sri lanka",
    "airport transfer company",
    "airport transfer service",
    "airport transfer shuttle",
    "airport transfer sri lanka",
    "airport transfers near me",
    "airport transfers sri lanka",
    "airport transport",
    "airport transport near me",
    "airport transport service",
    "airport travel",
    "bandaranaike international airport taxi",
    "best airport transfer",
    "best airport transfers sri lanka",
    "best taxi service",
    "best taxi service near me",
    "book a taxi near me",
    "book airport transfer",
    "book cab to airport",
    "book car to airport",
    "book minicab",
    "book ride to airport",
    "book transport to airport",
    "book van to airport",
    "booking airport",
    "booking airport transfers",
    "booking shuttle service",
    "booking taxi",
    "booking taxi service",
    "booking transfer",
    "cab booking",
    "cab booking near me",
    "cab booking sri lanka",
    "cab booking to airport",
    "cab companies near me",
    "cab for airport drop",
    "cab from airport",
    "cab near me",
    "cab number",
    "cab ride to airport",
    "cab service",
    "cab service colombo",
    "cab service near me",
    "cab service to airport",
    "cab service to the airport",
    "cab taxi",
    "cab taxi service",
    "call taxi",
    "call taxi near me",
    "car service to airport",
    "cheap airport taxi",
    "cheap airport taxi sri lanka",
    "cheap cabs",
    "cheap cabs near me",
    "cheap taxi",
    "cheap taxi near me",
    "cheap taxi near me cash",
    "cheapest taxi service near me",
    "city airport taxis",
    "city airport taxis reviews",
    "city airport transfers",
    "city cab",
    "city taxis",
    "cmb airport taxi",
    "colombo airport transfer",
    "colombo to galle taxi",
    "colombo to kandy taxi",
    "drop taxi",
    "fort taxi",
    "home to airport transfers",
    "international airport transfers",
    "international taxi",
    "international taxi service",
    "katunayake airport taxi prices",
    "kdh van taxi sri lanka",
    "mini cab",
    "mini cab near me",
    "minicab near me",
    "minivan taxi",
    "my taxi",
    "my transfers",
    "near me taxi",
    "one way cab",
    "one way drop taxi",
    "one way taxi",
    "online cab booking",
    "order taxi",
    "order taxi online",
    "pre book airport tax",
    "pre book taxi",
    "private chauffeur sri lanka",
    "private taxi",
    "private taxi hire",
    "private taxi near me",
    "private taxi service",
    "reading taxis",
    "reserve a taxi to the airport",
    "reserve taxi to airport",
    "schedule cab to airport",
    "schedule taxi to airport",
    "schiphol taxi service",
    "service cab",
    "service to airport",
    "shuttle booking",
    "shuttle bus",
    "shuttle services",
    "shuttle taxi service",
    "shuttle transfers sri lanka",
    "silver cab",
    "silver service taxi",
    "sri lanka airport",
    "sri lanka airport booking shuttle service",
    "sri lanka airport taxi",
    "sri lanka airport taxi price",
    "sri lanka airport taxi service",
    "sri lanka taxi",
    "taxi airport booking",
    "taxi app",
    "taxi around me",
    "taxi at airport",
    "taxi best",
    "taxi booking",
    "taxi booking near me",
    "taxi booking online",
    "taxi booking service",
    "taxi cab",
    "taxi cab companies",
    "taxi cab near me",
    "taxi cab service",
    "taxi cab service near me",
    "taxi cab to airport",
    "taxi call",
    "taxi car",
    "taxi companies near me",
    "taxi company",
    "taxi contact",
    "taxi contact number",
    "taxi cost",
    "taxi fare",
    "taxi firm",
    "taxi firms",
    "taxi firms near me",
    "taxi for airport drop",
    "taxi for airport transfer",
    "taxi for the airport",
    "taxi from here",
    "taxi from my location",
    "taxi hire",
    "taxi in airport",
    "taxi in sri lanka",
    "taxi near airport",
    "taxi near me",
    "taxi nearby",
    "taxi number",
    "taxi number near me",
    "taxi numbers",
    "taxi online",
    "taxi pick up",
    "taxi places",
    "taxi prices",
    "taxi quote",
    "taxi rates",
    "taxi reading",
    "taxi rental",
    "taxi reservation",
    "taxi ride",
    "taxi ride to airport",
    "taxi service",
    "taxi service colombo",
    "taxi service from airport",
    "taxi service near me",
    "taxi service sri lanka",
    "taxi service to the airport",
    "taxi shuttle",
    "taxi shuttle service",
    "taxi shuttle to airport",
    "taxi sri lanka",
    "taxi telephone number",
    "taxi to airport",
    "taxi to airport booking",
    "taxi to airport cost",
    "taxi to airport from my location",
    "taxi to airport near me",
    "taxi to terminal 5",
    "taxi transfer",
    "taxi transfer sri lanka",
    "taxi transfers",
    "taxi transport",
    "taxi van",
    "taxi van to airport",
    "taxi vans",
    "taxis on booking",
    "taxis service",
    "the airport taxi",
    "transfer booking",
    "transportation to airport",
    "travel to airport",
    "Airport Taxi Sri Lanka",
    "Airport Taxi Service",
    "Taxi Service Sri Lanka",
    "Airport Cab Booking",
    "Airport Taxi Transfers",
    "Airport Transfers Sri Lanka",
    "Booking Airport Transfers",
    "Airport Cab Service",
    "Cab Booking Sri Lanka",
    "Airport Shuttle Sri Lanka",
    "Airport Shuttle Service",
    "Taxi Transfer Sri Lanka",
    "Airport Transfer Service",
    "Airport Car Service",
    "Airport Transport Service",
    "Taxi Service to the Airport",
    "Shuttle Transfers Sri Lanka",
    "Best Airport Transfers Sri Lanka",
    "Cab Service to Airport",
    "Airport Chauffeur Service",
    "Taxi Van to Airport",
    "Sri Lanka Airport Taxi Price",
    "Airport Transfer Sri Lanka",
    "Airport Taxi Service near me",
    "Taxi Airport Booking",
    "Airport Pick Up Service",
    "Airport Taxi Price List",
    "Cheap Airport Taxi Sri Lanka",
    "Airport Transfer Shuttle",
    "Cab Service Colombo",
    "Airport Transfer Colombo Sri Lanka",
    "Taxi Service Sri Lanka",
    "Taxi in Sri Lanka",
    "Airport Shuttle Service near me",
    "Taxi for Airport Transfer",
    "Katunayake airport taxi prices",
    "Airport taxi fare",
    "Colombo Airport Transfer",
    "CMB Airport Taxi",
    "Private Chauffeur Sri Lanka",
    "KDH Van Taxi Sri Lanka",
    "Colombo to Kandy taxi",
    "Colombo to Galle taxi",
    "Bandaranaike International Airport taxi",
    "7 seater taxi",
    "8 seater taxi",
    "affordable airport transfer",
    "affordable taxi near me",
    "airport bus",
    "airport booking taxi",
    "airport cab",
    "airport cab booking",
    "airport cab service",
    "airport cabs",
    "airport cabs near me",
    "airport car booking",
    "airport car service",
    "airport chauffeur service",
    "airport drop cab",
    "airport drop off service",
    "airport drop off taxi",
    "airport drop service",
    "airport hire",
    "airport limo service",
    "airport limousine",
    "airport minicab",
    "airport pick up",
    "airport pick up service",
    "airport pickup and drop off service",
    "airport price list",
    "airport rides",
    "airport service",
    "airport shuttle",
    "airport shuttle booking",
    "airport shuttle lax",
    "airport shuttle near me",
    "airport shuttle seatac",
    "airport shuttle service",
    "airport shuttle service near me",
    "airport shuttle sri lanka",
    "airport taxi",
    "airport taxi booking",
    "airport taxi fare",
    "airport taxi flat rate",
    "airport taxi hire",
    "airport taxi near me",
    "airport taxi phone number",
    "airport taxi pick up",
    "airport taxi pickup",
    "airport taxi price",
    "airport taxi price list",
    "airport taxi prices",
    "airport taxi quote",
    "airport taxi rates",
    "airport taxi reviews",
    "airport taxi schiphol",
    "airport taxi service",
    "airport taxi service near me",
    "airport taxi sri lanka",
    "airport taxi transfer",
    "airport taxi transfers",
    "airport taxi transfers reviews",
    "airport taxi transport",
    "airport taxi van",
    "airport taxi with car seat",
    "airport to airport shuttle",
    "airport to hotel transfer sri lanka",
    "airport transfer",
    "airport transfer colombo sri lanka",
    "airport transfer company",
    "airport transfer service",
    "airport transfer shuttle",
    "airport transfer sri lanka",
    "airport transfers near me",
    "airport transfers sri lanka",
    "airport transport",
    "airport transport near me",
    "airport transport service",
    "airport travel",
    "all inclusive sri lanka airport taxi",
    "anantara resort airport transfer",
    "arugam bay airport taxi",
    "bandaranaike international airport taxi",
    "batticaloa airport taxi",
    "bentota airport transfer",
    "best airport transfer",
    "best airport transfers sri lanka",
    "best taxi service",
    "best taxi service near me",
    "bia airport taxi",
    "bia to colombo taxi fare",
    "book a black cab",
    "book a taxi near me",
    "book adam's peak taxi",
    "book airport transfer",
    "book cab to airport",
    "book car to airport",
    "book minicab",
    "book ride to airport",
    "book taxi online sri lanka",
    "book transport to airport",
    "book van to airport",
    "booking airport",
    "booking airport transfers",
    "booking shuttle service",
    "booking taxi",
    "booking taxi service",
    "booking transfer",
    "cab booking",
    "cab booking near me",
    "cab booking sri lanka",
    "cab booking to airport",
    "cab companies near me",
    "cab for airport drop",
    "cab from airport",
    "cab near me",
    "cab number",
    "cab ride to airport",
    "cab service",
    "cab service colombo",
    "cab service near me",
    "cab service to airport",
    "cab service to the airport",
    "cab taxi",
    "cab taxi service",
    "call a cab",
    "call a cab near me",
    "call a taxi near me",
    "call taxi",
    "call taxi near me",
    "car service to airport",
    "cheap airport taxi",
    "cheap airport taxi sri lanka",
    "cheap airport transfers",
    "cheap cabs",
    "cheap cabs near me",
    "cheap taxi",
    "cheap taxi near me",
    "cheap taxi near me cash",
    "cheapest airport taxi sri lanka",
    "cheapest taxi service near me",
    "cinnamon grand airport transfer",
    "city airport taxis",
    "city airport taxis reviews",
    "city airport transfers",
    "city cab",
    "city taxi",
    "city taxis",
    "cmb airport taxi",
    "colombo airport transfer",
    "colombo city taxi",
    "colombo lotus tower taxi",
    "colombo to ella taxi",
    "colombo to galle taxi",
    "colombo to kandy taxi",
    "colombo to mirissa taxi",
    "colombo to negombo taxi",
    "colombo to sigiriya taxi",
    "comfort taxi booking",
    "corporate cabs",
    "dambulla airport transfer",
    "digital nomad airport transfer sri lanka",
    "drop taxi",
    "eco friendly taxi sri lanka",
    "ella airport transfer",
    "executive taxi",
    "fixed rate airport taxi sri lanka",
    "fort taxi",
    "galle face hotel airport transfer",
    "galle fort taxi service",
    "go airport shuttle",
    "hambantota airport taxi",
    "hikkaduwa airport transfer",
    "hilton colombo airport taxi",
    "home to airport transfers",
    "hotel to airport transfer sri lanka",
    "hybrid taxi sri lanka",
    "i need a cab",
    "i need a ride to the airport",
    "i need a taxi",
    "international airport transfers",
    "international taxi",
    "international taxi service",
    "jaffna airport taxi",
    "jetwing colombo airport transfer",
    "kalutara airport transfer",
    "kandy to colombo airport shuttle",
    "kangaroo cabs airport booking",
    "katunayake airport taxi prices",
    "kdh van taxi sri lanka",
    "local cab company",
    "local cab service near me",
    "local cabs",
    "local cabs near me",
    "local taxi",
    "local taxi number",
    "local taxi service",
    "local taxi service near me",
    "long distance taxi",
    "long distance taxi service",
    "luxury airport transfers sri lanka",
    "luxury cab service",
    "luxury taxi",
    "luxury taxi service",
    "mattala airport taxi",
    "maxi cab booking",
    "maxi taxi near me",
    "mini cab",
    "mini cab near me",
    "minicab near me",
    "minibus taxi",
    "minibus taxi near me",
    "minivan taxi",
    "mirissa airport transfer",
    "mount lavinia taxi",
    "my taxi",
    "my transfers",
    "near me taxi",
    "negombo airport taxi",
    "one way cab",
    "one way drop taxi",
    "one way taxi",
    "online cab booking",
    "order taxi",
    "order taxi online",
    "pasikudah airport transfer",
    "pick me taxi sri lanka",
    "pinnawala elephant orphanage taxi",
    "pre book airport taxi",
    "pre book taxi",
    "private chauffeur sri lanka",
    "private taxi",
    "private taxi hire",
    "private taxi near me",
    "private taxi service",
    "private transfer sri lanka",
    "reading taxis",
    "reliable airport taxi colombo",
    "reserve a taxi to the airport",
    "reserve taxi to airport",
    "safe taxi sri lanka for female travelers",
    "schedule cab to airport",
    "schedule taxi to airport",
    "schiphol taxi service",
    "service cab",
    "service to airport",
    "shangri-la colombo airport transfer",
    "shuttle booking",
    "shuttle bus",
    "shuttle services",
    "shuttle taxi service",
    "shuttle transfers sri lanka",
    "sigiriya airport transfer",
    "silver cab",
    "silver service cabs",
    "silver service taxi",
    "sri lanka airport",
    "sri lanka airport booking shuttle service",
    "sri lanka airport taxi",
    "sri lanka airport taxi price",
    "sri lanka airport taxi service",
    "sri lanka taxi",
    "sustainable tourism taxi sri lanka",
    "tangalle airport transfer",
    "taxi airport booking",
    "taxi app",
    "taxi around me",
    "taxi at airport",
    "taxi best",
    "taxi booking",
    "taxi booking near me",
    "taxi booking online",
    "taxi booking service",
    "taxi cab",
    "taxi cab companies",
    "taxi cab near me",
    "taxi cab service",
    "taxi cab service near me",
    "taxi cab to airport",
    "taxi call",
    "taxi car",
    "taxi close to me",
    "taxi companies near me",
    "taxi company",
    "taxi contact",
    "taxi contact number",
    "taxi cost",
    "taxi estimate",
    "taxi fare",
    "taxi firm",
    "taxi firms",
    "taxi firms near me",
    "taxi for airport drop",
    "taxi for airport transfer",
    "taxi for the airport",
    "taxi from here",
    "taxi from my location",
    "taxi hire",
    "taxi in airport",
    "taxi in sri lanka",
    "taxi near airport",
    "taxi near by",
    "taxi near me",
    "taxi nearby",
    "taxi number",
    "taxi number near me",
    "taxi numbers",
    "taxi online",
    "taxi phone number",
    "taxi phone number near me",
    "taxi pick up",
    "taxi places",
    "taxi price estimate",
    "taxi prices",
    "taxi prices near me",
    "taxi quote",
    "taxi rates",
    "taxi reading",
    "taxi rental",
    "taxi reservation",
    "taxi ride",
    "taxi ride to airport",
    "taxi service",
    "taxi service colombo",
    "taxi service from airport",
    "taxi service near me",
    "taxi service near me prices",
    "taxi service sri lanka",
    "taxi service to the airport",
    "taxi shuttle",
    "taxi shuttle service",
    "taxi shuttle to airport",
    "taxi sri lanka",
    "taxi telephone number",
    "taxi to airport",
    "taxi to airport booking",
    "taxi to airport cost",
    "taxi to airport from my location",
    "taxi to airport near me",
    "taxi to terminal 5",
    "taxi transfer",
    "taxi transfer sri lanka",
    "taxi transfers",
    "taxi transport",
    "taxi van",
    "taxi van to airport",
    "taxi vans",
    "taxis on booking",
    "taxis service",
    "the airport taxi",
    "transfer booking",
    "transportation to airport",
    "travel to airport",
    "unawatuna airport taxi",
    "weligama airport transfer",
    "wellness retreat airport transfer sri lanka",
    "wheelchair taxi",
    "wheelchair taxi near me",
    "wheelchair taxi service near me",
    "yala national park taxi",
    "24/7 airport pickup sri lanka",
    "adangama private taxi",
    "airport greeting service colombo",
    "airport paging service sri lanka",
    "airport taxi with english speaking driver",
    "airport to ahangama taxi",
    "airport to dambulla cave temple transfer",
    "airport to dickwella taxi",
    "airport to galle expressway taxi",
    "airport to hikkaduwa private car",
    "airport to kandy 90 minute transfer",
    "airport to lions rock sigiriya shuttle",
    "airport to nilaveli beach transfer",
    "airport to polonnaruwa taxi",
    "airport to trincomalee private transfer",
    "airport transfer with flight tracking",
    "all inclusive taxi rates sri lanka",
    "anuradhapura to airport drop",
    "arrival hall meet and greet sri lanka",
    "arugam bay surf taxi",
    "axio taxi sri lanka",
    "bandaranaike arrival terminal pickup",
    "best price airport drop negombo",
    "best transportation service colombo",
    "bia to ahangama taxi fare",
    "bia to colombo taxi price 2026",
    "bia to hikkaduwa van hire",
    "bia to kandy shuttle service",
    "bia to sigiriya private driver",
    "bia to unawatuna taxi",
    "budget taxi sri lanka",
    "business travel airport transfer colombo",
    "car and driver hire sri lanka",
    "ceylon airport taxi service",
    "cheap kandy to airport shuttle",
    "colombo airport departure taxi",
    "colombo airport to any hotel transfer",
    "colombo airport to ella with stops",
    "colombo airport to galle fort taxi",
    "colombo airport to tangalle small group transfer",
    "colombo airport to yala safari taxi",
    "colombo city to bia transfer",
    "comfortable sedan for airport transfer",
    "customizable sri lanka tours with driver",
    "daily kandy to colombo airport shuttle",
    "dual ac van hire sri lanka",
    "early morning airport taxi colombo",
    "english speaking chauffeur sri lanka",
    "expressway tolls included taxi",
    "family van for airport transfer sri lanka",
    "fixed price airport taxi colombo",
    "galle to bia taxi fare",
    "hambantota to colombo airport transfer",
    "hightop kdh van sri lanka",
    "honda fit shuttle taxi sri lanka",
    "honda vezel airport taxi",
    "hybrid car taxi sri lanka",
    "islandwide transportation sri lanka",
    "kandy to bia private transfer",
    "kdh 14 seater van sri lanka",
    "kdh flat roof van for hire",
    "kdh luxury van sri lanka",
    "last minute airport cab booking",
    "late night airport pickup colombo",
    "low emission transport sri lanka",
    "luxury suv airport transfer sri lanka",
    "matara to airport expressway taxi",
    "mattala airport to colombo taxi",
    "mirissa to bia taxi price",
    "mr taxi sri lanka",
    "multi day tour with private driver",
    "negombo beach to airport taxi",
    "no hidden charges airport taxi",
    "nuwara eliya to airport private car",
    "on time airport drop off",
    "personalized name sign airport pickup",
    "premium airport car service colombo",
    "private car charter with driver sri lanka",
    "private driver guide sri lanka",
    "private transfer colombo to mirissa",
    "private transfer from airport to weligama",
    "professional chauffeur service sri lanka",
    "punctuall airport pickup colombo",
    "ranweli tours airport transfer",
    "reliable airport cab service negombo",
    "reliable islandwide transfers sri lanka",
    "safari jeep to airport transfer",
    "safe taxi for solo female travelers sri lanka",
    "scenic route airport transfer ella",
    "shared shuttle colombo airport",
    "sigiriya to airport private taxi",
    "sigiriya to kandy private transfer",
    "small group airport transfer sri lanka",
    "sri lanka airport drop price list",
    "sri lanka airport pickup assistant",
    "sri lanka airport taxi whatsapp number",
    "sri lanka budget taxi alto",
    "sri lanka luxury van hire with driver",
    "sri lanka mini car taxi",
    "sri lanka private tour and taxi",
    "sri lanka travel trends 2026 transport",
    "sriluxe tours airport transfer",
    "suzuki every van for hire sri lanka",
    "suzuki wagon r taxi sri lanka",
    "taj samudra to airport taxi",
    "tangalle to bia taxi fare",
    "taxi with bottled water sri lanka",
    "top rated airport transfer sri lanka",
    "toyota axio airport taxi",
    "toyota hiace for airport transfer",
    "toyota prius airport taxi sri lanka",
    "transparent pricing airport taxi",
    "trusted taxi provider sri lanka",
    "unawatuna to airport expressway cab",
    "vantage airport taxi sri lanka",
    "weligama to colombo airport taxi",
    "whatsapp taxi booking sri lanka",
    "yala to airport private transfer",
    "24/7 airport pickup sri lanka",
    "adangama private taxi",
    "airport greeting service colombo",
    "airport paging service sri lanka",
    "airport taxi with english speaking driver",
    "airport to ahangama taxi",
    "airport to dambulla cave temple transfer",
    "airport to dickwella taxi",
    "airport to galle expressway taxi",
    "airport to hikkaduwa private car",
    "airport to kandy 90 minute transfer",
    "airport to lions rock sigiriya shuttle",
    "airport to nilaveli beach transfer",
    "airport to polonnaruwa taxi",
    "airport to trincomalee private transfer",
    "airport transfer with flight tracking",
    "all inclusive taxi rates sri lanka",
    "anuradhapura to airport drop",
    "arrival hall meet and greet sri lanka",
    "arugam bay surf taxi",
    "axio taxi sri lanka",
    "bandaranaike arrival terminal pickup",
    "best price airport drop negombo",
    "best transportation service colombo",
    "bia to ahangama taxi fare",
    "bia to colombo taxi price 2026",
    "bia to hikkaduwa van hire",
    "bia to kandy shuttle service",
    "bia to sigiriya private driver",
    "bia to unawatuna taxi",
    "budget taxi sri lanka",
    "business travel airport transfer colombo",
    "car and driver hire sri lanka",
    "ceylon airport taxi service",
    "cheap kandy to airport shuttle",
    "colombo airport departure taxi",
    "colombo airport to any hotel transfer",
    "colombo airport to ella with stops",
    "colombo airport to galle fort taxi",
    "colombo airport to tangalle small group transfer",
    "colombo airport to yala safari taxi",
    "colombo city to bia transfer",
    "comfortable sedan for airport transfer",
    "customizable sri lanka tours with driver",
    "daily kandy to colombo airport shuttle",
    "dual ac van hire sri lanka",
    "early morning airport taxi colombo",
    "english speaking chauffeur sri lanka",
    "expressway tolls included taxi",
    "family van for airport transfer sri lanka",
    "fixed price airport taxi colombo",
    "galle to bia taxi fare",
    "hambantota to colombo airport transfer",
    "hightop kdh van sri lanka",
    "honda fit shuttle taxi sri lanka",
    "honda vezel airport taxi",
    "hybrid car taxi sri lanka",
    "islandwide transportation sri lanka",
    "kandy to bia private transfer",
    "kdh 14 seater van sri lanka",
    "kdh flat roof van for hire",
    "kdh luxury van sri lanka",
    "last minute airport cab booking",
    "late night airport pickup colombo",
    "low emission transport sri lanka",
    "luxury suv airport transfer sri lanka",
    "matara to airport expressway taxi",
    "mattala airport to colombo taxi",
    "mirissa to bia taxi price",
    "mr taxi sri lanka",
    "multi day tour with private driver",
    "negombo beach to airport taxi",
    "no hidden charges airport taxi",
    "nuwara eliya to airport private car",
    "on time airport drop off",
    "personalized name sign airport pickup",
    "premium airport car service colombo",
    "private car charter with driver sri lanka",
    "private driver guide sri lanka",
    "private transfer colombo to mirissa",
    "private transfer from airport to weligama",
    "professional chauffeur service sri lanka",
    "punctuall airport pickup colombo",
    "ranweli tours airport transfer",
    "reliable airport cab service negombo",
    "reliable islandwide transfers sri lanka",
    "safari jeep to airport transfer",
    "safe taxi for solo female travelers sri lanka",
    "scenic route airport transfer ella",
    "shared shuttle colombo airport",
    "sigiriya to airport private taxi",
    "sigiriya to kandy private transfer",
    "small group airport transfer sri lanka",
    "sri lanka airport drop price list",
    "sri lanka airport pickup assistant",
    "sri lanka airport taxi whatsapp number",
    "sri lanka budget taxi alto",
    "sri lanka luxury van hire with driver",
    "sri lanka mini car taxi",
    "sri lanka private tour and taxi",
    "sri lanka travel trends 2026 transport",
    "sriluxe tours airport transfer",
    "suzuki every van for hire sri lanka",
    "suzuki wagon r taxi sri lanka",
    "taj samudra to airport taxi",
    "tangalle to bia taxi fare",
    "taxi with bottled water sri lanka",
    "top rated airport transfer sri lanka",
    "toyota axio airport taxi",
    "toyota hiace for airport transfer",
    "toyota prius airport taxi sri lanka",
    "transparent pricing airport taxi",
    "trusted taxi provider sri lanka",
    "unawatuna to airport expressway cab",
    "vantage airport taxi sri lanka",
    "weligama to colombo airport taxi",
    "whatsapp taxi booking sri lanka",
    "yala to airport private transfer",
    "24/7 airport pickup sri lanka",
    "accessible taxi sri lanka",
    "affordable airport transfer",
    "affordable taxi near me",
    "ahangama private taxi",
    "air conditioned van hire sri lanka",
    "airport arrival meet and greet colombo",
    "airport greeting service sri lanka",
    "airport limo service",
    "airport limousine",
    "airport paging service sri lanka",
    "airport pickup assistant sri lanka",
    "airport taxi with english speaking driver",
    "airport to ahangama taxi",
    "airport to dambulla cave temple transfer",
    "airport to dickwella taxi",
    "airport to galle expressway taxi",
    "airport to hikkaduwa private car",
    "airport to kandy 90 minute transfer",
    "airport to lions rock sigiriya shuttle",
    "airport to nilaveli beach transfer",
    "airport to polonnaruwa taxi",
    "airport to trincomalee private transfer",
    "airport transfer with flight tracking",
    "all inclusive sri lanka airport taxi",
    "all inclusive taxi rates sri lanka",
    "anantara resort airport transfer",
    "anuradhapura to airport drop",
    "arrival hall meet and greet sri lanka",
    "arugam bay airport taxi",
    "arugam bay surf taxi",
    "axio taxi sri lanka",
    "bandaranaike arrival terminal pickup",
    "batticaloa airport taxi",
    "bentota airport transfer",
    "best price airport drop negombo",
    "best transportation service colombo",
    "bia airport taxi",
    "bia to ahangama taxi fare",
    "bia to colombo taxi price 2026",
    "bia to hikkaduwa van hire",
    "bia to kandy shuttle service",
    "bia to sigiriya private driver",
    "bia to unawatuna taxi",
    "book a black cab",
    "book adam's peak taxi",
    "book taxi online sri lanka",
    "budget taxi sri lanka",
    "business travel airport transfer colombo",
    "car and driver hire sri lanka",
    "ceylon airport taxi service",
    "cheap airport transfers",
    "cheap kandy to airport shuttle",
    "cheapest airport taxi sri lanka",
    "cinnamon grand airport transfer",
    "colombo airport departure taxi",
    "colombo airport to any hotel transfer",
    "colombo airport to ella with stops",
    "colombo airport to galle fort taxi",
    "colombo airport to tangalle small group transfer",
    "colombo airport to yala safari taxi",
    "colombo city taxi",
    "colombo city to bia transfer",
    "colombo lotus tower taxi",
    "colombo to ella taxi",
    "colombo to mirissa taxi",
    "colombo to negombo taxi",
    "colombo to sigiriya taxi",
    "comfort taxi booking",
    "comfortable sedan for airport transfer",
    "corporate cabs",
    "customizable sri lanka tours with driver",
    "dambulla airport transfer",
    "decision detox travel sri lanka",
    "digital nomad airport transfer sri lanka",
    "dual ac van hire sri lanka",
    "early morning airport taxi colombo",
    "eco friendly taxi sri lanka",
    "ella airport transfer",
    "english speaking chauffeur sri lanka",
    "executive taxi",
    "expressway tolls included taxi",
    "family van for airport transfer sri lanka",
    "fixed price airport taxi colombo",
    "fixed rate airport taxi sri lanka",
    "galle face hotel airport transfer",
    "galle fort taxi service",
    "galle to bia taxi fare",
    "hambantota airport taxi",
    "hambantota to colombo airport transfer",
    "hikkaduwa airport transfer",
    "hightop kdh van sri lanka",
    "hilton colombo airport taxi",
    "honda fit shuttle taxi sri lanka",
    "honda vezel airport taxi",
    "hotel to airport transfer sri lanka",
    "hybrid car taxi sri lanka",
    "hybrid taxi sri lanka",
    "i need a ride to the airport",
    "islandwide transportation sri lanka",
    "jaffna airport taxi",
    "jetwing colombo airport transfer",
    "kalutara airport transfer",
    "kandy to bia private transfer",
    "kandy to colombo airport shuttle",
    "kangaroo cabs airport booking",
    "kdh 14 seater van sri lanka",
    "kdh flat roof van for hire",
    "kdh luxury van sri lanka",
    "last minute airport cab booking",
    "late night airport pickup colombo",
    "low emission transport sri lanka",
    "luxury airport transfers sri lanka",
    "luxury cab service",
    "luxury suv airport transfer sri lanka",
    "luxury taxi service",
    "matara to airport expressway taxi",
    "mattala airport taxi",
    "mattala airport to colombo taxi",
    "maxi cab booking",
    "mirissa airport transfer",
    "mirissa to bia taxi price",
    "mount lavinia taxi",
    "multi day tour with private driver",
    "negombo airport taxi",
    "negombo beach to airport taxi",
    "no hidden charges airport taxi",
    "nuwara eliya to airport private car",
    "on time airport drop off",
    "pasikudah airport transfer",
    "personalized name sign airport pickup",
    "pick me taxi sri lanka",
    "pinnawala elephant orphanage taxi",
    "premium airport car service colombo",
    "private car charter with driver sri lanka",
    "private driver guide sri lanka",
    "private transfer colombo to mirissa",
    "private transfer from airport to weligama",
    "private transfer sri lanka",
    "professional chauffeur service sri lanka",
    "punctuall airport pickup colombo",
    "regenerative travel sri lanka transport",
    "reliable airport taxi colombo",
    "reliable islandwide transfers sri lanka",
    "safari jeep to airport transfer",
    "safe taxi for solo female travelers sri lanka",
    "scenic route airport transfer ella",
    "shangri-la colombo airport transfer",
    "shared shuttle colombo airport",
    "sigiriya airport transfer",
    "sigiriya to airport private taxi",
    "sigiriya to kandy private transfer",
    "silver service cabs",
    "small group airport transfer sri lanka",
    "sri lanka airport drop price list",
    "sri lanka airport taxi whatsapp number",
    "sri lanka budget taxi alto",
    "sri lanka luxury van hire with driver",
    "sri lanka mini car taxi",
    "sri lanka private tour and taxi",
    "sri lanka travel trends 2026 transport",
    "sriluxe tours airport transfer",
    "sustainable tourism taxi sri lanka",
    "suzuki every van for hire sri lanka",
    "suzuki wagon r taxi sri lanka",
    "taj samudra to airport taxi",
    "tangalle airport transfer",
    "tangalle to bia taxi fare",
    "taxi with bottled water sri lanka",
    "top rated airport transfer sri lanka",
    "toyota axio airport taxi",
    "toyota hiace for airport transfer",
    "toyota prius airport taxi sri lanka",
    "transparent pricing airport taxi",
    "trusted taxi provider sri lanka",
    "unawatuna airport taxi",
    "unawatuna to airport expressway cab",
    "vantage airport taxi sri lanka",
    "weligama airport transfer",
    "weligama to colombo airport taxi",
    "wellness retreat airport transfer sri lanka",
    "whatsapp taxi booking sri lanka",
    "wheelchair taxi sri lanka",
    "yala national park taxi",
    "yala to airport private transfer",
    ],
    authors: [{ name: 'Airport Taxis Pvt (Ltd)' }],
    creator: 'Airport Taxis Pvt (Ltd)',
    publisher: 'Airport Taxis Pvt (Ltd)',
    formatDetection: {
        email: false,
        address: false,
        telephone: false,
    },
    metadataBase: new URL('https://srilankantaxi.lk'),
    alternates: {
        canonical: 'https://srilankantaxi.lk',
    },
    openGraph: {
        title: '🚖 Airport Taxis Sri Lanka - #1 Trusted Airport Transfers & Multi-Day Tours',
        description: 'Instant Booking! Reliable 24/7 airport transfers from Colombo Airport (CMB). Professional drivers, comfortable vehicles (Mini Car, Sedan, KDH Van). Best rates guaranteed for all-island tours.',
        url: 'https://srilankantaxi.lk',
        siteName: 'Airport Taxis Pvt (Ltd)',
        images: [
            {
                url: '/og-image.jpg',
                width: 1200,
                height: 630,
                alt: 'Airport Taxis Sri Lanka - Your Trusted Airport Transfer Partner',
            },
        ],
        locale: 'en_US',
        type: 'website',
    },

    twitter: {
        card: 'summary_large_image',
        title: '🚖 Airport Taxis Sri Lanka - Premium Airport Rides & Tours',
        description: 'Trusted 24/7 airport transfers & tours. Professional drivers, instant confirmation, best rates guaranteed!',
        images: ['/og-image.jpg'],
    },

    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
            'max-video-preview': -1,
            'max-image-preview': 'large',
            'max-snippet': -1,
        },
    },
    icons: {
        icon: [
            { url: '/favicon.ico' },
            { url: '/logo.png', type: 'image/png' },
        ],
        apple: '/logo.png',
    },
}

// JSON-LD Structured Data
const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
        {
            '@type': 'LocalBusiness',
            '@id': 'https://srilankantaxi.lk/#localbusiness',
            name: 'Airport Taxis Pvt (Ltd)',
            image: 'https://srilankantaxi.lk/og-image.jpg',
            url: 'https://srilankantaxi.lk',
            telephone: '+94716885880',
            priceRange: '$$',
            address: {
                '@type': 'PostalAddress',
                streetAddress: 'Bandaranaike International Airport',
                addressLocality: 'Katunayake',
                postalCode: '11450',
                addressCountry: 'LK'
            },
            geo: {
                '@type': 'GeoCoordinates',
                latitude: 7.1811,
                longitude: 79.8837
            },
            openingHoursSpecification: {
                '@type': 'OpeningHoursSpecification',
                dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                opens: '00:00',
                closes: '23:59'
            },
            aggregateRating: {
                '@type': 'AggregateRating',
                ratingValue: 5.0,
                reviewCount: 296
            },
            review: [
                {
                    "@type": "Review",
                    "author": "James Wilson",
                    "datePublished": "2024-03-15",
                    "reviewBody": "Excellent service from Colombo Airport to Ella. The driver was professional and the car was very comfortable.",
                    "reviewRating": {
                        "@type": "Rating",
                        "ratingValue": "5"
                    }
                },
                {
                    "@type": "Review",
                    "author": "Sarah Miller",
                    "datePublished": "2024-02-28",
                    "reviewBody": "Best airport taxi service in Sri Lanka. Fixed price as promised and no hidden charges. Highly recommended!",
                    "reviewRating": {
                        "@type": "Rating",
                        "ratingValue": "5"
                    }
                }
            ]
        },
        {
            '@type': 'TaxiService',
            name: 'Airport Taxis Pvt (Ltd)',
            description: 'Premium airport transfer and private tour service in Sri Lanka across Colombo, Kandy, Galle and more.',
            url: 'https://srilankantaxi.lk',
            provider: { '@id': 'https://srilankantaxi.lk/#localbusiness' },
            hasOfferCatalog: {
                "@type": "OfferCatalog",
                "name": "Airport Transfer Services",
                "itemListElement": [
                    {
                        "@type": "Offer",
                        "itemOffered": {
                            "@type": "Service",
                            "name": "Colombo Airport to Colombo City Transfer",
                            "description": "Fast and reliable transfer from CMB Airport to Colombo hotels."
                        }
                    },
                    {
                        "@type": "Offer",
                        "itemOffered": {
                            "@type": "Service",
                            "name": "Colombo Airport to Kandy Transfer",
                            "description": "Comfortable 3-hour journey to the hill capital Kandy."
                        }
                    },
                    {
                        "@type": "Offer",
                        "itemOffered": {
                            "@type": "Service",
                            "name": "Colombo Airport to Galle Transfer",
                            "description": "Smooth highway transfer to the historic city of Galle."
                        }
                    }
                ]
            }
        },
        {
            '@type': 'Organization',
            '@id': 'https://srilankantaxi.lk/#organization',
            name: 'Airport Taxis Pvt (Ltd)',
            url: 'https://srilankantaxi.lk',
            logo: {
                '@type': 'ImageObject',
                'url': 'https://srilankantaxi.lk/logo.png',
                'width': 512,
                'height': 512
            },
            address: {
                '@type': 'PostalAddress',
                streetAddress: '118/5 St. Joseph Street, Grandpass',
                addressLocality: 'Colombo',
                postalCode: '01400',
                addressCountry: 'LK'
            },
            contactPoint: {
                '@type': 'ContactPoint',
                telephone: '+94716885880',
                contactType: 'customer service',
                areaServed: 'LK',
                availableLanguage: ['English', 'Sinhala']
            },
            sameAs: [
                'https://www.facebook.com/airporttaxistours',
                'https://www.instagram.com/airporttaxistours',
                'https://wa.me/94716885880'
            ]
        }
    ]
}

import { CurrencyProvider } from '../context/CurrencyContext'

// ... existing imports

import { Inter, Montserrat } from 'next/font/google'

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap',
})

const montserrat = Montserrat({
    subsets: ['latin'],
    variable: '--font-montserrat',
    display: 'swap',
})

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning className={`${inter.variable} ${montserrat.variable}`}>
            <head>
                <meta name="theme-color" content="#059669" />
                <link rel="preconnect" href="https://srilankantaxi.lk" />
                <link rel="dns-prefetch" href="https://srilankantaxi.lk" />
                <link rel="preconnect" href="https://ipapi.co" />
                <link rel="dns-prefetch" href="https://ipapi.co" />
                <link rel="preconnect" href="https://api.exchangerate-api.com" />
                <link rel="dns-prefetch" href="https://api.exchangerate-api.com" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <link rel="dns-prefetch" href="https://fonts.googleapis.com" />
                <script
                    type="application/ld+json"
                    dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
                />
            </head>
            <body className="font-sans antialiased selection:bg-emerald-600 selection:text-white transition-colors duration-300">
                <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>

                    <AuthProvider>
                        <CurrencyProvider>
                            <div className="sticky top-0 z-[100] w-full flex flex-col">
                                <CategoryBar />
                                <Navbar />
                                <OfferMarquee />
                            </div>
                            <main>{children}</main>
                            <FloatingContact />
                            <LiveChatWidget />
                            <Footer />
                        </CurrencyProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
